### ISSUE TITLE
添加新star后 partial-sync 执行出错

### ISSUE THREAD

**Issue by jostyee** [lcjnil/github-notion-star#7]
今天给两个项目加星：
https://github.com/hashicorp/go-retryablehttp
https://github.com/sony/gobreaker

然后action运行就报错了：
```
@notionhq/client warn: request fail {
  code: 'validation_error',
  message: 'Primary Language is not a property that exists. Repository Topics is not a property that exists.'
}

/home/runner/work/github-notion-star/github-notion-star/node_modules/@notionhq/client/src/errors.ts:240
    return new APIResponseError({
           ^
APIResponseError: Primary Language is not a property that exists. Repository Topics is not a property that exists.
    at Object.buildRequestError (/home/runner/work/github-notion-star/github-notion-star/node_modules/@notionhq/client/src/errors.ts:240:12)
    at Client.request (/home/runner/work/github-notion-star/github-notion-star/node_modules/@notionhq/client/src/Client.ts:157:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Notion.insertPage (/home/runner/work/github-notion-star/github-notion-star/libs/notion.ts:77:22)
    at partialSync (/home/runner/work/github-notion-star/github-notion-star/main.ts:24:9)
Error: Process completed with exit code 1.
```

**Comment by lcjnil** [comment]
@jostyee 在 #4 里面新增了两个字段，所以需要添加一下

可以参考首页的 Readme https://github.com/lcjnil/github-notion-star#breaking-change

**Comment by jostyee** [comment]
@lcjnil 谢谢，现在可以了，之前不该手欠没看commit log直接同步upstream的。。
