### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by colgin** [lcjnil/github-notion-star#8]
Notion: error from recover cache Error: ENOENT: no such file or directory, open '/home/runner/work/github-notion-star/github-notion-star/.cache/notion-page.json'

/home/runner/work/github-notion-star/github-notion-star/main.ts:30
ENVS.forEach((env) => {
     ^
AssertionError [ERR_ASSERTION]: NOTION_API_KEY must be added
    at /home/runner/work/github-notion-star/github-notion-star/main.ts:31:11
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/runner/work/github-notion-star/github-notion-star/main.ts:30:6)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module.m._compile (/home/runner/work/github-notion-star/github-notion-star/node_modules/ts-node/src/index.ts:1225:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (/home/runner/work/github-notion-star/github-notion-star/node_modules/ts-node/src/index.ts:1228:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at Object.get (/home/runner/work/github-notion-star/github-notion-star/libs/cache.ts:18:31)
    at new Notion (/home/runner/work/github-notion-star/github-notion-star/libs/notion.ts:19:22)
    at Object.<anonymous> (/home/runner/work/github-notion-star/github-notion-star/libs/notion.ts:142:23)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module.m._compile (/home/runner/work/github-notion-star/github-notion-star/node_modules/ts-node/src/index.ts:1225:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (/home/runner/work/github-notion-star/github-notion-star/node_modules/ts-node/src/index.ts:1228:12)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/runner/work/github-notion-star/github-notion-star/.cache/notion-page.json'
}
Notion: restored from cache, count is 0

看起来是因为NOTION_API_KEY 没有添加，但是，我是加了的。可以帮忙看下吗？

**Comment by lcjnil** [comment]
NOTION_API_KEY 应该加在 secrets 里面，是这么操作的么？

**Comment by colgin** [comment]
哦，我搞错地方了。我重新弄了一下，好了。感谢你的项目和帮助
